# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build  Image'
  inputs:
    containerRegistry: 'fonacregistry'
    repository: 'nodejs-server'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: 'Push Image'
  inputs:
    containerRegistry: 'fonacregistry'
    repository: 'nodejs-server'
    command: 'push'

- task: CmdLine@2
  inputs:
    script: 'sed -i ''s/latest/$(Build.BuildId)/g'' create-nodejs-service-manifest.yaml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'create-nodejs-service-manifest.yaml'
    ArtifactName: 'YAML'
    publishLocation: 'Container'

