apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: node-deployment
  labels:
    app: node

spec:
  # modify replicas according to your case
  replicas: 1 
  selector:
    matchLabels:
      app: node
   # We do daily rollouts, limit the revision history to two weeks of num releases 
   # as we don't expect to roll back beyond that. 
  revisionHistoryLimit: 14
  # deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  # the Deployment must wait for 60 seconds after seeing a Pod become healthy before moving on to updating the next Pod
  minReadySeconds: 60
    # sets the progress deadline to 10 minutes
    # If any particular stage in the rollout fails to progress in 10 minutes, then the Deployment is marked as failed, 
    # and all attempts to move the Deployment forward are halted
    # Not the overall length of the deployment! Anytime the deployment creates or deletes a Pod
  progressDeadlineSeconds: 600
  # pod template
  template:
    metadata:
      labels:
        app: node
    spec:
      # pod contains 1 container
      containers:
      - name: node
        image: fonacregistry.azurecr.io/nodejs-server:latest
        livenessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3 
        livenessProbe:
          httpGet:
            path: /
            port: 22137
          periodSeconds: 10
          failureThreshold: 3 
          successThreshold: 1 
        resources:
          requests:  #request a Pod with  a minimum of 0.1 of a core and 250 MB of memory
            cpu: "500m"
            memory: "128Mi"
          limits:    #add a limit of 1.0 CPU and 256 MB of memory
            cpu: "1000m"   
            memory: "256Mi"

        # container opens port 22137
        ports:
        - containerPort: 22137
          name: http
          protocol: TCP            
---
apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: node-service
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  type: LoadBalancer
  ports:
    - name: http
      port: 22137
      targetPort: 22137
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node
